#!/bin/sh /etc/rc.common
                                                                               
# init file for 'ping_status_LED'

START=99
STOP=01
start() {
        echo "Starting Online Status Monitor"
        [ -f /usr/bin/ping_status_LED ] && /usr/bin/ping_status_LED &        
}         

stop() {
        echo "Stopping Online Status Monitor"          
        killall ping_status_LED                
}