#!/bin/sh /etc/rc.common
                                                                               
# structure from http://wiki.openwrt.org/oldwiki/mod.led.sysloadled?s%5B%5D=led
 
START=99
STOP=01
start() {
        echo "Starting Online Status Monitor"
        [ -f /usr/bin/ping_status2LED.sh ] && /usr/bin/ping_status2LED.sh &        
}                
 
stop() {      
        echo "Stopping Online Status Monitor"          
        killall ping_status2LED.sh                
} 