#!/bin/ash
 
# ONLINE STATUS 2 LED SCRIPT #
### a small script which tries to ping a target (google)
### and turns on a LED when it was successful.

### inspired by http://wiki.openwrt.org/oldwiki/mod.led.sysloadled

##### CONFIG #####
 
## location of the LED in /proc (depends on router model)
LED_PATH="/sys/devices/platform/leds-gpio/leds/tp-link:blue:system"       
LED_INIT=0   ## LED is off by default
LED_OFF=0    ## which value turns LED on
LED_ON=255   ## look it up in $LED_PATH/max_brightness (we want the script to do less)
SLEEP=3      ## how many seconds to wait between checks
WAIT=3       ## how long to wait for the Ping

# HELPER VARS -- don't edit if you don't have to
LED=""$LED_PATH"/brightness"
PING_TARGET="8.8.8.8"  ## Google's DNS -- if it's down the net is boring anyhow
OUTPUT="> /dev/null" ## make empty for debug output

# DEBUG section
#echo "LED is $LED."
#echo "Current brightness is $(cat $LED)"
#OUTPUT=" " #uncommment this to enable output to shell


##### MAIN PROGRAMM ######
 
# initial LED status (off by default)
echo $LED_INIT > $LED
 
# LOOP IT FOREVER
while true ; do
    ping -q -c1 -W $WAIT $PING_TARGET > /dev/null && echo $LED_ON > $LED || echo $LED_OFF > $LED
    sleep $SLEEP;
done
 
exit 0